### ISSUE TITLE
using polymorph variants makes the interface unnecessarily complex

### ISSUE THREAD

**Issue by UnixJunkie** [mwweissmann/ocaml-posix-semaphore#2]
If you are interested, I might contribute a simpler interface as an addition (so that current users will not
be disturbed).

**Comment by mwweissmann** [comment]
The current interface just fits my requirements, but I'm open to an interface with exceptions or something (with a JaneStreet-style "_exn" suffix). I'd prefer a solution where there only exists one C function and the interface thing is a pure OCaml wrapper around the other solution -- but I'd guess you had that in mind anyway.

**Comment by UnixJunkie** [comment]
Currently, the interface I use looks like this:

    module Sem : sig
      exception Sem_except of string
      type 'a t
      val create: unit -> [> `Named] t
      val close: [> `Named] t -> unit
      val unlink: [> `Named] t -> unit
      val post: [> `Named] t -> unit
      val wait: [> `Named] t -> unit
      val try_wait: [> `Named] t -> bool
    end

**Comment by UnixJunkie** [comment]
only tray_wait is not supposed to raise an exception

**Comment by UnixJunkie** [comment]
Here is the implementation:

    module Sem = struct
    
      let count = ref 0
    
      open Posix_semaphore
    
      type 'a t = { name: string; (* name in filesystem *)
                    sem: 'a semaphore } (* actual semaphore *)
    
      let constr name sem =
        { name; sem }
    
      exception Sem_except of string
    
      let unwrap = function
        | Result.Error (`EUnix err) -> raise (Sem_except (Unix.error_message err))
        | Result.Ok x -> x
    
      (* default count is 0 *)
      let create () =
        let name = sprintf "/ocaml_libparany_pid_%d_sem_%d" !count (Unix.getpid ()) in
        incr count;
        (* printf "sem_name: %s\n%!" name; *)
        let sem = unwrap (sem_open name Unix.[O_RDWR; O_CREAT] 0o600 0) in
        constr name sem
    
      let close x =
        unwrap (sem_close x.sem)
    
      let unlink x =
        unwrap (sem_unlink x.name)
    
      (* add 1 to sem *)
      let post x =
        unwrap (sem_post x.sem)
    
      let wait x =
        unwrap (sem_wait x.sem)
    
      let try_wait x =
        match sem_trywait x.sem with
        | Result.Error _ -> false (* did not get sem *)
        | Result.Ok () -> true (* got it *)
    
    end

**Comment by UnixJunkie** [comment]
the true interface probably needs a functor since we are parametrized by the semaphore type (named or unnamed)

**Comment by UnixJunkie** [comment]
I only require named semaphore however

**Comment by mwweissmann** [comment]
I added exception-based functions to the API -- just use the one with the "_exn"-suffix to get an exception instead of the "result" value. I'll release a new version 0.5.0 with the addition.
https://github.com/mwweissmann/ocaml-posix-semaphore/commit/a72e12b88e78f814b9b7521a11dfc0044ffd3ace
